### ISSUE TITLE
BDD

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-Tabecai#29]
Não entregue pela equipe

**Comment by YuriBre** [comment]
Olá, professor
O BDD foi entregue, estava na pasta [PBB](https://github.com/mdsreq-fga-unb/2023.2-Tabecai/blob/docs/docs/pbb_heatnet.md), conforme indicado na [pasta da entrega 3](https://github.com/mdsreq-fga-unb/2023.2-Tabecai/blob/docs/docs/entrega_3.md).
