### ISSUE TITLE
ER

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-Tabecai#7]
As seções:
3.8.2 Atividades do Processo de Engenharia de Requisitos
3.8.3 Requisitos e Planejamento

Não estão em acordo com o material da disciplina.
Outra coisa, não faz nenhum sentido essa organização de cascata + RAD que vcs apresentam. Por favor, refaçam, ou expliquem melhor como isso vai funcionar, na prática do projeto.

**Comment by Maiconrq** [comment]
Decidido em grupo e consertado as seções:
3.8.2 Atividades do Processo de Engenharia de Requisitos;
3.8.3 Requisitos e Planejamento;
Atualizado também a seção 3.7.
